language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements_test.txt
  - pip install codecov
  - python setup.py develop
script:
  - py.test --cov=./comfortsmother -vv -s tests
after_success:
  - codecov